### ISSUE TITLE
Camera Intents

### ISSUE THREAD

**Issue by ArshiyanAlam** [adityag1998/NaviCam#1]
- [x] noise filter with object-count dictionary. 
-increment/decrement dict as per current frame result.
-for key in dict : 
        if (count>=5) {count=5; add key to objectSet}
        if (count<=0) {delete key} .
-send intent if objectSet is different from last sent set intent.

- [x] send empty list for no object, for no text Or on camera close

**Comment by adityag1998** [comment]
This is in progress. A similar behaviour would be mimicked by DummyCamera App.

**Comment by adityag1998** [comment]
1. The above mentioned TODO's have been implemented successfully.
2. To manage image noise, 2 static THRESHOLD CONSTANTS have been used.
3. Opening new issue for text handling as that is not efficient yet (Rapid Noise, alignment and readability)
